# Generated by Django 3.2.3 on 2021-05-14 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("durin", "0002_auto_20210513_1527"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="authtoken",
            name="unique token for user per client",
        ),
        migrations.RemoveField(
            model_name="authtoken",
            name="client",
        ),
        migrations.RemoveField(
            model_name="authtoken",
            name="user",
        ),
        migrations.AddField(
            model_name="userclient",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="durin.client",
            ),
        ),
        migrations.AddField(
            model_name="userclient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="authtoken",
            name="userclient",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authtoken",
                to="durin.userclient",
            ),
        ),
        migrations.AddConstraint(
            model_name="userclient",
            constraint=models.UniqueConstraint(
                fields=("user", "client"), name="unique user client pair"
            ),
        ),
    ]
